#!/usr/bin/env node
//
// Build the toolbar icon font.
//
// Material Symbols is fetched here, at build time, and subset to the handful of
// glyphs the toolbar actually uses. The application never contacts Google: a
// runtime webfont request would send the user's IP address to a third party on
// every launch, which is exactly what we must not do. The bundled subset also
// happens to be a few kilobytes instead of several megabytes.
//
// Run `node scripts/fetch-icons.mjs`. Needs uv on PATH, which provides
// fonttools ephemerally - it is a build tool and has no business in either the
// application's Python environment or package.json.

import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const FONT_DIR = join(ROOT, "src", "fonts");
const CSS_PATH = join(ROOT, "src", "icons.css");

const VARIANT = "MaterialSymbolsOutlined%5BFILL%2CGRAD%2Copsz%2Cwght%5D";
const BASE = "https://raw.githubusercontent.com/google/material-design-icons/master/variablefont";

// Toolbar action -> Material Symbols glyph name.
const ICONS = {
  new: "note_add",
  open: "file_open",
  save: "save",
  // Circled: the file from disk, in its own process. Plain: the buffer, on the
  // kernel, beside Run Cell and Run Selection which are also the kernel's.
  "run-file": "play_circle",
  "run-all": "play_arrow",
  "run-cell": "skip_next",
  "run-sel": "playlist_play",
  interrupt: "stop_circle",
  restart: "restart_alt",
  refresh: "refresh",
  "new-folder": "create_new_folder",
  chevron: "chevron_right",
  sidebar: "left_panel_open",
  upgrade: "deployed_code_update",
  "theme-light": "light_mode",
  "theme-dark": "dark_mode",
  info: "info",
  close: "close",
  copy: "content_copy",
  settings: "tune",
  // The command palette. ">_" is what every editor uses for "type a command".
  command: "terminal",
  // Debugging. The step glyphs are Material Symbols' own, drawn for exactly
  // this: an arrow hopping over, into and out of a line.
  debug: "bug_report",
  "debug-continue": "resume",
  "debug-step-over": "step_over",
  "debug-step-into": "step_into",
  "debug-step-out": "step_out",
  "debug-stop": "stop",
  // The reset_camera shortcut beside the console tabs: the camera resets on
  // the next show, or is kept where it is.
  "camera-reset": "flip_camera_ios",
  "camera-keep": "photo_camera",
};

async function download(url, description) {
  process.stdout.write(`  fetching ${description}… `);
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`${response.status} ${response.statusText} for ${url}`);
  }
  const buffer = Buffer.from(await response.arrayBuffer());
  console.log(`${(buffer.length / 1024).toFixed(0)} kB`);
  return buffer;
}

function parseCodepoints(text) {
  const map = new Map();
  for (const line of text.split("\n")) {
    const [name, codepoint] = line.trim().split(/\s+/);
    if (name !== undefined && codepoint !== undefined) {
      map.set(name, codepoint);
    }
  }
  return map;
}

console.log("Building the Material Symbols subset");

mkdirSync(FONT_DIR, { recursive: true });

const codepoints = parseCodepoints(
  (await download(`${BASE}/${VARIANT}.codepoints`, "codepoint table")).toString("utf8"),
);

const wanted = [];
for (const [action, glyph] of Object.entries(ICONS)) {
  const codepoint = codepoints.get(glyph);
  if (codepoint === undefined) {
    throw new Error(`Material Symbols has no glyph named "${glyph}" (for ${action})`);
  }
  wanted.push({ action, glyph, codepoint });
}

const fontPath = join(FONT_DIR, "material-symbols-full.ttf");
writeFileSync(fontPath, await download(`${BASE}/${VARIANT}.ttf`, "variable font"));

const outputPath = join(FONT_DIR, "material-symbols-subset.woff2");
const unicodes = wanted.map((icon) => `U+${icon.codepoint}`).join(",");

console.log(`  subsetting to ${wanted.length} glyphs (${unicodes})`);
execFileSync(
  "uv",
  [
    "run",
    "--quiet",
    "--with",
    "fonttools[woff]",
    "pyftsubset",
    fontPath,
    `--unicodes=${unicodes}`,
    "--flavor=woff2",
    `--output-file=${outputPath}`,
    // Ligatures are how Material Symbols is normally used - you write the icon
    // name as text. Subsetting by codepoint drops the name glyphs that make
    // that work, so the markup references codepoints directly instead and the
    // layout tables are not needed.
    "--layout-features=",
    "--no-hinting",
    "--desubroutinize",
  ],
  { stdio: "inherit" },
);

// The multi-megabyte source is only an intermediate; keep the tree clean.
execFileSync("rm", ["-f", fontPath]);

const rules = wanted
  .map(
    (icon) =>
      `/* ${icon.glyph} */\n.icon-${icon.action}::before {\n  content: "\\${icon.codepoint}";\n}`,
  )
  .join("\n\n");

writeFileSync(
  CSS_PATH,
  `/* Generated by scripts/fetch-icons.mjs - do not edit by hand.
 *
 * A Material Symbols subset containing only the toolbar's glyphs, bundled with
 * the application. Nothing is fetched from Google at runtime.
 */

@font-face {
  font-family: "Material Symbols";
  font-style: normal;
  font-weight: 100 700;
  src: url("./fonts/material-symbols-subset.woff2") format("woff2");
}

.icon::before {
  font-family: "Material Symbols";
  font-weight: normal;
  font-style: normal;
  font-size: 18px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  white-space: nowrap;
  direction: ltr;
  -webkit-font-smoothing: antialiased;
  /* The variable axes still exist in the subset; pin them to the flat,
     unfilled, regular-weight look the rest of the UI uses. */
  font-variation-settings: "FILL" 0, "wght" 400, "GRAD" 0, "opsz" 24;
}

${rules}
`,
);

console.log(`  wrote ${outputPath}`);
console.log(`  wrote ${CSS_PATH}`);
if (!existsSync(outputPath)) {
  throw new Error("Subsetting produced no output");
}
